version: 2

updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    labels:
      - "type: maintenance"
      - "priority: low"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - "type: maintenance"
      - "priority: low"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - "type: maintenance"
      - "priority: low"
