name: Ruff

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          pyproject-file: pyproject.toml
      - uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
      - run: uv sync --only-group ruff --frozen
      - run: uv run ruff check
      - run: uv run ruff format --check
