name: Ruff

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ruff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - check
          - "format --check"
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          pyproject-file: pyproject.toml
      - uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - run: uv sync --only-group ruff --frozen
      - run: uv run ruff ${{ matrix.command }}
